server:
  port: 8088
  servlet:
    context-path: /api
spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
  application:
    name: TeamShare-Backend
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 使用Druid数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME} # 数据库用户名
    password: ${MYSQL_PASSWORD} # 数据库密码
    druid:
      # 连接池配置：大小，最小，最大
      initial-size: 10
      min-idle: 5
      max-active: 20
      # 连接等待超时时间
      max-wait: 30000
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    database: ${REDIS_DATABASE}
    lettuce:
      pool:
        max-active: 32
        max-idle: 16
        min-idle: 8
        time-between-eviction-runs: 10s
# 配置QQ邮件信息
  mail:
    host: ${EMAIL_HOST} # 邮箱服务器地址
    username: ${EMAIL_USERNAME} # 发送者信箱
    password: ${EMAIL_PASSWORD} # 授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #springboot2.6以上的版本整合swagger或knife4j需要更改匹配策略
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0